# # generated by Git for Windows
# test -f ~/.profile && . ~/.profile
# test -f ~/.bashrc && . ~/.bashrc
# xport PATH=/usr/local/share/python:$PATH
# export PYTHONPATH=/usr/local/lib/python:$PYTHONPATH
# PYTHONPATH=$PYTHONPATH:/System/Library/Frameworks/Python.framework/Versions/3.6.1/lib/python3/site-packages/
# export PATH=$PATH:/usr/local/bin
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi